name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  industrial_ci:
    name: ${{ matrix.env.CI_NAME }}
    strategy:
      fail-fast: false
      matrix:
        env:
          - {CI_NAME: clang-format,
             OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             BADGE: bionic,
             CLANG_FORMAT_CHECK: file,
             CLANG_FORMAT_VERSION: 8}
          - {CI_NAME: Bionic-Cuda10.2,
             OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             ROSDEP_SKIP_KEYS: nvidia-cuda-dev iwyu,
             BADGE: bionic,
             ADDITIONAL_DEBS: iwyu,
             UPSTREAM_WORKSPACE: 'github:ros-industrial/cmake_common_scripts#master',
             TARGET_CMAKE_ARGS: "-DBUILD_TESTING=ON -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/",
             DOCKER_PULL: false,
             DOCKER_IMAGE: "schornakj/yak_ci:bionic-cuda10.2",
             CTEST_OUTPUT_ON_FAILURE: true,
             AFTER_SCRIPT: 'cd $target_ws/build/yak && ctest -V'}
          - {CI_NAME: Bionic-Cuda9.2,
             OS_NAME: ubuntu,
             OS_CODE_NAME: bionic,
             ROS_DISTRO: melodic,
             ROSDEP_SKIP_KEYS: nvidia-cuda-dev iwyu,
             BADGE: bionic,
             ADDITIONAL_DEBS: iwyu,
             UPSTREAM_WORKSPACE: 'github:ros-industrial/cmake_common_scripts#master',
             TARGET_CMAKE_ARGS: "-DBUILD_TESTING=ON -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/",
             DOCKER_PULL: false,
             DOCKER_IMAGE: "schornakj/yak_ci:bionic-cuda9.2",
             CTEST_OUTPUT_ON_FAILURE: true,
             AFTER_SCRIPT: 'cd $target_ws/build/yak && ctest -V'}
          - {CI_NAME: Xenial-Cuda10.2,
             OS_NAME: ubuntu,
             OS_CODE_NAME: xenial,
             ROS_DISTRO: kinetic,
             ROSDEP_SKIP_KEYS: nvidia-cuda-dev libpcl-all-dev iwyu,
             BADGE: xenial,
             ADDITIONAL_DEBS: iwyu,
             UPSTREAM_WORKSPACE: 'github:ros-industrial/cmake_common_scripts#master',
             TARGET_CMAKE_ARGS: "-DBUILD_TESTING=ON -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/",
             DOCKER_PULL: false,
             DOCKER_IMAGE: "schornakj/yak-1:xenial-cuda10.2",
             CTEST_OUTPUT_ON_FAILURE: true,
             AFTER_SCRIPT: 'cd $target_ws/build/yak && ctest -V'}
          - {CI_NAME: Xenial-Cuda9.2,
             OS_NAME: ubuntu,
             OS_CODE_NAME: xenial,
             ROS_DISTRO: kinetic,
             ROSDEP_SKIP_KEYS: nvidia-cuda-dev libpcl-all-dev iwyu,
             BADGE: xenial,
             ADDITIONAL_DEBS: iwyu,
             UPSTREAM_WORKSPACE: 'github:ros-industrial/cmake_common_scripts#master',
             TARGET_CMAKE_ARGS: "-DBUILD_TESTING=ON -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/",
             DOCKER_PULL: false,
             DOCKER_IMAGE: "schornakj/yak-1:xenial-cuda9.2",
             CTEST_OUTPUT_ON_FAILURE: true,
             AFTER_SCRIPT: 'cd $target_ws/build/yak && ctest -V'}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
